services:
  frontend:
    container_name: kupipodariday-frontend
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - internet
    restart: on-failure

  backend:
    container_name: kupipodariday-backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"
    networks:
      - internal-network
      - internet
    depends_on:
      - database
    restart: on-failure

  database:
    container_name: kupipodariday-postgres
    image: "postgres:latest"
    env_file:
      - ./backend/.env
    environment:
      PGDATA: ${PGDATA}
    networks:
      - internal-network
    restart: on-failure
    volumes:
      - ./pg-data:${PGDATA}

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
